### ISSUE TITLE
Only the first word is shown for devices with multiple word names

### ISSUE THREAD

**Issue by koolskateguy89** [melianmiko/ulauncher-bluetoothd#1]
Also I could only get the extension to work literally once. It seems Ulauncher doesn't recognise the extension anymore or something idk.

**Comment by melianmiko** [comment]
Fixed, please open ulauncher settings and check updates for extension.

But i don't know why extensions works literally once. On my PC it works fine after any updates/reboot/reinstall.
Could you please give more information: OS version, ulauncher version?

**Comment by koolskateguy89** [comment]
It works perfectly now. The extension was always working but as it doesn't show anything if there are no paired Bluetooth devices I thought it wasn't working. I apologise, this was my error. Thanks for fixing it so quickly it's a brilliant extension.
