### ISSUE TITLE
check bluetooth status

### ISSUE THREAD

**Issue by kush4gra** [melianmiko/ulauncher-bluetoothd#2]
can we perform a bluetooth  power check everytime we have to connect to a device ? and turn it on by default before connecting to a device

**Comment by melianmiko** [comment]
Now my extension will unblock Bluetooth via rfkill before connection.
Please upgrade extension from Ulauncher settings and check.

**Comment by kush4gra** [comment]
Thanks, afaik unblocking using rfkill won't turn on bluetooth by itself. It has to be done using bluetoothctl or more preferably using a dbus call like

`dbus-send --system --dest=org.bluez --print-reply /org/bluez/${ADDRESS} org.freedesktop.DBus.Properties.Set string:org.bluez.${ADAPTER} string:Powered variant:boolean:${DESIRED_STATE}`

**Comment by melianmiko** [comment]
I tried to use `bluetoothctl power` command, but it not work for me. If bluetooth is disabled in GNOME Shell menu, this command returns error:

```bash
melianmiko@mmk-pc:~$ bluetoothctl power on
Failed to set power on: org.bluez.Error.Blocked
```
DBus-send also throws error, but `rfkill unblock` works fine.

**Comment by kush4gra** [comment]
hey sorry to repoen this, using ulauncher after a bit of time, just noticed you removed rfkill check again.

since i use blueman, which use rfkill to enable/disable bluetooth, this extension cant renanable bluetooth in that situation.

can you pls add that check again

**Comment by melianmiko** [comment]
I'll check that when will time...
