### ISSUE TITLE
A KeyError is thrown when adding the plugin

### ISSUE THREAD

**Issue by fl3x1324** [melianmiko/ulauncher-bluetoothd#3]
### Steps to reproduce
- Add the extension by copy/pasting the repo URL
- Press "Save"

### Environment
**OS**: _Arch Linux_
**Kernel**: _5.12.4-arch1-2_
**DE**: _GNOME 40_
**Python**: _3.9.5_

### Error output
```
Message: 'com.github.melianmiko.ulauncher-bluetoothd'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.melianmiko.ulauncher-bluetoothd'

```

**Comment by melianmiko** [comment]
I can't reproduce this error, in my OS this extension works fine.
Which version of ULauncher do you have? Did you have this error with other extensions?

![2021-05-22_10-26](https://user-images.githubusercontent.com/67851274/119213321-78fda580-bae8-11eb-96fa-8c4be16448cd.png)
![2021-05-22_10-27](https://user-images.githubusercontent.com/67851274/119213322-7a2ed280-bae8-11eb-8650-60b38b7b90da.png)

**Comment by fl3x1324** [comment]
I've got Ulauncher 5.11.0 + Extension API v2.0.0
and yes it happens with all extensions. Am I missing some runtime dep?
Adding the extension works for me. Pressing "Save" or trying the keyword in the launcher breaks it.
Here's my setup:
![Screenshot from 2021-05-22 16-01-21](https://user-images.githubusercontent.com/9042848/119227544-18d22800-bb17-11eb-90ae-a54a3d8ed674.png)

**Comment by melianmiko** [comment]
Sorry, I don't know. But this isn't my issue.
