### ISSUE TITLE
Notification Issues

### ISSUE THREAD

**Issue by kush4gra** [melianmiko/ulauncher-bluetoothd#7]
I am getting unreadable characters in the output of second notification , somehow utf-8 isnt decoding the output properly. 

Also It will be a lot better, if we can simply send notification like "Device_name Disconnected/Connected" instead of the current notification which is just a information mess. 

![image](https://user-images.githubusercontent.com/36916613/132867445-4bf251ff-062e-497b-b0a6-8ea74017bb2d.png)

**Comment by melianmiko** [comment]
Fixed. Please update this extension from Ulauncher settings and check now =)

**Comment by kush4gra** [comment]
yeah, working now. thanks
